spring:
  application:
    name: satellite-io-service
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true