server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : satellite-io-service
          uri: http://localhost:8091
          predicates:
            - Path=/satellite-io/**
        - id : telemetry-service
          uri: http://localhost:8092
          predicates:
            - Path=/tm/**
        - id : telecommand-service
          uri: http://localhost:8093
          predicates:
            - Path=/tc/**